[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
selene = { source = "Kampfkarren/selene", version = "x" }
wally = { source = "UpliftGames/wally", version = "0.3.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.11.2" }
