name: CI

on:
  push:
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Initialize Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selene on src
        run: selene src

  stylua:
      name: Format Source
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.4

        - name: Initialize Foreman
          uses: rojo-rbx/setup-foreman@v1.0.1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Run StyLua on src
          run: stylua src
