name: publish

on:
  push:
    branches: [ master ]

jobs:
  wally:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialize Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish Nature2D to Wally
        env:
          WALLY_AU: ${{ secrets.WALLY_AU }}
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish
