# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '24 16 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "Looks like there hasn't been much activity going on here! In order to prevent clutter and purge inactive issues, this issue will be closed if it remains in the state of inactivity. If your issue has not been solved, you can open another issue to address your query! Be sure to format your issue correctly to help us review and process your issue faster!"
        stale-pr-message: "Looks like there hasn't been much activity going on here! In order to prevent clutter and purge inactive pull requests, this pull request will be closed if it remains in the state of inactivity. You can open another pull request if you wish to! Be sure to format your pull request correctly to help us review and process your pull request faster!"
        stale-issue-label: 'state: inactive'
        stale-pr-label: 'state: inactive'
